// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyapxkpwwyvqlrtrlefc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5YXB4a3B3d3l2cWxydHJsZWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDEzNjksImV4cCI6MjA2Mjc3NzM2OX0.E5cAykePSmSDkpWSYZsViJrOf_p-m1XVy2Doozij0AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);